version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: naman-ent-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa_secret
      POSTGRES_DB: medusa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: naman-ent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: naman-ent-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: naman_ent_meili_master_key_change_in_prod
      MEILI_ENV: development
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
